# Generated by Django 3.2.7 on 2021-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Produs',
            },
        ),
    ]
